# Generated by Django 5.0.3 on 2024-03-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Listings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make", models.CharField(max_length=30)),
                ("model", models.CharField(max_length=30)),
                ("year", models.IntegerField(default=2010)),
                ("size_type", models.CharField(max_length=30)),
                ("color", models.CharField(max_length=30)),
                ("mileage", models.IntegerField(default=100)),
            ],
        ),
    ]
