# Generated by Django 5.0.3 on 2024-04-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_reviews"),
    ]

    operations = [
        migrations.CreateModel(
            name="RentalApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner_username", models.CharField(default="", max_length=100)),
                ("borrower_username", models.CharField(default="", max_length=100)),
                ("cost_per_day", models.FloatField(default=50.0)),
                ("vehicle_listing_id", models.IntegerField(default=-1)),
                ("is_approved", models.BooleanField(default=False)),
                ("is_denied", models.BooleanField(default=False)),
                ("req_lease_length_days", models.IntegerField(default=2)),
            ],
        ),
        migrations.AddField(
            model_name="listings",
            name="cost_per_day",
            field=models.FloatField(default=50.0),
        ),
        migrations.AddField(
            model_name="listings",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="listings",
            name="vehicle_listing_id",
            field=models.IntegerField(default=-1),
        ),
    ]
