# Generated by Django 5.0.3 on 2024-04-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0004_rentalapplication_listings_cost_per_day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalapplication",
            name="application_id",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="reviews",
            name="review_id",
            field=models.IntegerField(default=-1),
        ),
    ]
