# Generated by Django 5.0.3 on 2024-04-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0005_rentalapplication_application_id_reviews_review_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalapplication",
            name="profile_id",
            field=models.IntegerField(default=-1),
        ),
    ]
