# Generated by Django 5.0.3 on 2024-04-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0006_rentalapplication_profile_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="RentalTansactionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner_username", models.CharField(default="", max_length=100)),
                ("borrower_username", models.CharField(default="", max_length=100)),
                ("cost_per_day", models.FloatField(default=0.0)),
                ("vehicle_listing_id", models.IntegerField(default=-1)),
                ("lease_length_days", models.IntegerField(default=2)),
                ("is_returned", models.BooleanField(default=False)),
                ("application_id", models.IntegerField(default=-1)),
            ],
        ),
    ]
