# Generated by Django 5.0.3 on 2024-04-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_rentalapplication_message"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reviews",
            old_name="review_text",
            new_name="borrower_review_text",
        ),
        migrations.RenameField(
            model_name="reviews",
            old_name="recipient",
            new_name="borrower_username",
        ),
        migrations.RenameField(
            model_name="reviews",
            old_name="sender",
            new_name="owner_username",
        ),
        migrations.AddField(
            model_name="reviews",
            name="borrower_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reviews",
            name="owner_review_text",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="reviews",
            name="owner_sent",
            field=models.BooleanField(default=False),
        ),
    ]
