# Generated by Django 5.0.3 on 2024-04-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0009_rename_review_text_reviews_borrower_review_text_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reviews",
            old_name="borrower_sent",
            new_name="is_published",
        ),
        migrations.RenameField(
            model_name="reviews",
            old_name="borrower_username",
            new_name="recipient",
        ),
        migrations.RenameField(
            model_name="reviews",
            old_name="borrower_review_text",
            new_name="review_text",
        ),
        migrations.RenameField(
            model_name="reviews",
            old_name="owner_username",
            new_name="sender",
        ),
        migrations.RemoveField(
            model_name="reviews",
            name="owner_review_text",
        ),
        migrations.RemoveField(
            model_name="reviews",
            name="owner_sent",
        ),
        migrations.AddField(
            model_name="reviews",
            name="application_id",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="reviews",
            name="make",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AddField(
            model_name="reviews",
            name="model",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AddField(
            model_name="reviews",
            name="req_lease_length_days",
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name="reviews",
            name="year",
            field=models.IntegerField(default=2010),
        ),
    ]
