# Generated by Django 5.0.3 on 2024-04-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_is_first_time_profile_sq1_profile_sq2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="is_first_time",
            field=models.BooleanField(default=True),
        ),
    ]
